package com.thom.core.tool;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

/**
 * Scans all Java source files under a given source root and generates a
 * SpotBugs include-filter XML containing every class that implements
 * AppBean or PageBean.
 *
 * Invoked automatically by the exec-maven-plugin at the prepare-package
 * phase, before SpotBugs runs at the package phase.
 *
 * Usage: FindBugsFilterGenerator <sourceRoot> <outputFile>
 *   sourceRoot  – path to src/main/java
 *   outputFile  – path to spotbugs/findbugs.xml
 */
public class FindBugsFilterGenerator {

    private static final List<String> TARGET_INTERFACES = List.of("AppBean", "PageBean");

    public static void main(String[] args) throws IOException {
        if (args.length < 2) {
            System.err.println("Usage: FindBugsFilterGenerator <sourceRoot> <outputFile>");
            System.exit(1);
        }

        Path sourceRoot = Paths.get(args[0]);
        Path outputFile = Paths.get(args[1]);

        List<String> implementors = scanForImplementors(sourceRoot);

        writeFilterXml(outputFile, implementors);

        System.out.printf("[FindBugsFilterGenerator] Generated %s with %d implementor(s):%n",
                outputFile, implementors.size());
        implementors.forEach(c -> System.out.println("  - " + c));
    }

    private static List<String> scanForImplementors(Path sourceRoot) throws IOException {
        List<String> implementors = new ArrayList<>();

        try (Stream<Path> paths = Files.walk(sourceRoot)) {
            paths.filter(p -> p.toString().endsWith(".java"))
                 .forEach(javaFile -> {
                     try {
                         CompilationUnit cu = StaticJavaParser.parse(javaFile);

                         String pkg = cu.getPackageDeclaration()
                                        .map(pd -> pd.getNameAsString())
                                        .orElse("");

                         cu.findAll(ClassOrInterfaceDeclaration.class).stream()
                           .filter(cls -> !cls.isInterface())
                           .filter(cls -> cls.getImplementedTypes().stream()
                               .anyMatch(t -> TARGET_INTERFACES.contains(t.getNameAsString())))
                           .map(cls -> pkg.isEmpty()
                                   ? cls.getNameAsString()
                                   : pkg + "." + cls.getNameAsString())
                           .forEach(implementors::add);

                     } catch (IOException e) {
                         throw new RuntimeException("Failed to parse: " + javaFile, e);
                     }
                 });
        }

        return implementors;
    }

    private static void writeFilterXml(Path outputFile, List<String> implementors) throws IOException {
        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<!-- Auto-generated by FindBugsFilterGenerator. Do not edit manually. -->\n");
        xml.append("<FindBugsFilter>\n\n");

        if (!implementors.isEmpty()) {
            xml.append("    <Match>\n");
            xml.append("        <Or>\n");
            for (String cls : implementors) {
                xml.append("            <Class name=\"").append(cls).append("\" />\n");
            }
            xml.append("        </Or>\n");
            xml.append("        <Bug pattern=\"SE_BAD_FIELD,SE_NO_SUITABLE_CONSTRUCTOR,")
               .append("SE_NO_SERIALVERSIONID,SE_BAD_FIELD_STORE\" />\n");
            xml.append("    </Match>\n\n");
        }

        xml.append("</FindBugsFilter>\n");

        Files.createDirectories(outputFile.getParent());
        Files.writeString(outputFile, xml.toString());
    }
}
